### ISSUE TITLE
vNAAATS Crash on Exit

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#119]
TTSIA, see image
![image](https://user-images.githubusercontent.com/56816890/130990979-0f4d5a34-a0f3-4b6b-a066-c5a50b42d021.png)

Due to this bug, the user is unable to save any files relating to the sector file before exiting EuroScope.

**Comment by aogden41** [comment]
fixed and closing
