### ISSUE TITLE
Copy FP-route to ManEntry

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#120]
TTSIA; Requesting a feature to be able to copy the automatically-detected route from aircraft's flight plan to the ManEntry route window.

**Comment by aogden41** [comment]
i have removed the man-entry window and instead replaced it with just the editable window you get between clicking submit on man entry and read back
it auto fills the track and the route and Read Back is only enabled when everything is filled out
also made the callsign rectangle a lighter colour if ReadBk has not been clicked
