### ISSUE TITLE
ManEntry route: lat/long points are displayed incorrectly

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#123]
![image](https://user-images.githubusercontent.com/56816890/132121374-3a5c5027-91b2-4984-9bc5-f2e206bccdd9.png)
![image](https://user-images.githubusercontent.com/56816890/132121380-4aed53b8-333d-4916-83aa-2a4cc6ffec3c.png)

**Comment by aogden41** [comment]
fixed and closing
