### ISSUE TITLE
CZQO Sector: Westound start appearing after 30W

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#124]
On CZQO, on CZQX Display setting, westbound aircraft from Shanwick airspace at 30W, aircraft only start appearing after 30W, at approx 32W or 33W. Would suggest for them to appear at 27W

https://user-images.githubusercontent.com/56816890/132121476-284ab34e-7a41-4f06-aa34-a6f4a7736b02.mp4

**Comment by aogden41** [comment]
fixed, I think? Idk hard to test but from what I can see it is fine now. Let me know

Closing
