### ISSUE TITLE
Request addition of BICC_FSS

### ISSUE THREAD

**Issue by phoenixegmh** [gander-oceanic-fir-vatsim/vatsim-NAAATS#60]
Good Day,

Request addition of support for BICC_FSS as an adjacent sector to Gander / Shanwick

**Comment by aogden41** [comment]
Hi, what exactly do you mean by this?

**Comment by phoenixegmh** [comment]
Hi Andrew,

I control BICC_FSS (Iceland Radio, Oceanic Clearances and Control) and have tried to integrate vNAAATS with the Iceland sector files so that it can be used there, but the position obviously does not appear within any drop down lists and when I connect to VATSIM in that live position, I am unable to see any aircraft (can see them as an OBS).

I am assuming that there's something related to sector ownership that's stopping this?

**Comment by aogden41** [comment]
Unfortunately the plugin is intimately attached to the Gander/Shanwick sector files, given that's what the software IRL is used for, it uses the sector file itself to determine whether aircraft are inbound, whether they are under radar coverage or not, etc. It is not possible to transpose it onto other stations yet, but it is planned for the future, as I do want to get rid of the reliance on specific sector files,

**Comment by phoenixegmh** [comment]
No problems, I had a feeling that was the case, thanks for the update
