### ISSUE TITLE
vNAAATS not always detecting "B1"?

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#74]
So my vNAAATS didn't detect the "B1" in the flight-plan remarks of an aircraft and marked it with a *, indicating it's not ADS-B capable. But then we had a look at the remarks and actually, his remarks were as follows:
`PBN/A1B1C1D1L1O1S1S2 DOF/210327 REG/GXWBA EET/CZQM0028 CZQX0116 47N050W0150 50N040W0237 EGGX0321 55N020W0401 EISN0431 EGTT0500 OPR/BA PER/D RALT/CYJT LPLA EINN RMK/TCAS SIMBRIEF /V/`

So there's probably something wrong that went there. Callsign BAW81 // A359/H.

**Comment by aogden41** [comment]
fixed!
