### ISSUE TITLE
1000ft-separated conflicts still appearing

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#78]
As you know, with the introduction of ADS-B/-C simulation, separation can now be minimum 1000ft. However, I still get conflict alerts despite this for such aircraft. Example: 

![image](https://user-images.githubusercontent.com/56816890/112837779-99872180-909c-11eb-9500-e15c368ac97a.png)

This shouldn't be occuring, as ADS-B/-C simulation is present, therefore, separation is maintained.

**Comment by aogden41** [comment]
I believe this is fixed, let me know if not
