### ISSUE TITLE
first update to network flight plan (copy) clears the route and can't be re-instantiated (route not being uplinked properly)

### ISSUE THREAD

**Issue by aogden41** [gander-oceanic-fir-vatsim/vatsim-NAAATS#89]
TTSIA - need to fix

**Comment by dsolesvik** [comment]
I knew it would do this, but I still thought that the interesting contents of the window after I clicked "Copy" would further help with resolving the bug. 
https://user-images.githubusercontent.com/56816890/120229565-b206ea00-c24d-11eb-9d1c-311daa36cf0a.mp4

**Comment by dsolesvik** [comment]
Fixed
