### ISSUE TITLE
(v2 Beta) Corrupt Font

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#91]
I believe in v2, the font is missing/corrupt, which was there in a version of v1 (can send that version).

v1: 
![image](https://user-images.githubusercontent.com/56816890/120007704-7adcd280-bfda-11eb-91f0-ed89b70db5e7.png)

v2:
![image](https://user-images.githubusercontent.com/56816890/120008351-2be36d00-bfdb-11eb-910a-906b1169396e.png)

**Comment by aogden41** [comment]
It's not corrupt, that's a result of my attempt to install the fonts internally without you needing to install it yourself, but it's not working properly. Not a priority issue for now.
