### ISSUE TITLE
(v2 Beta) Halo and PTL not working

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#92]
Unless I'm doing something wrong, in v2.0.0b, Halo and PTL aren't working. 
![image](https://user-images.githubusercontent.com/56816890/120049322-e5613300-c019-11eb-8c2f-fa709c7d79b6.png)

**Comment by aogden41** [comment]
Fixed, halo uses a distance radius in NM and ptl projects point in x minutes up to 60 minutes
