### ISSUE TITLE
(v2 Beta) ManEntry points displayed in the wrong order

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#93]
In the ManEntry route display, the latitude and longitudes are displayed the wrong way round. 

![image](https://user-images.githubusercontent.com/56816890/120050925-e183df80-c01e-11eb-977b-6a9385fcc1c6.png)

Should be:
PIKIL   20W  30W  40W  50W  DORYY
            57N    59N    59N    58N

**Comment by aogden41** [comment]
Fixed
