### ISSUE TITLE
(v2 Beta) Concorde Sierra Tracks missing in ManEntry

### ISSUE THREAD

**Issue by dsolesvik** [gander-oceanic-fir-vatsim/vatsim-NAAATS#98]
Close if it's already an issue.
Cannot enter Concorde Sierra Tracks
![image](https://user-images.githubusercontent.com/56816890/120225839-479e7b80-c246-11eb-8438-de06249a224b.png)

**Comment by aogden41** [comment]
duplicate, see issue #57
